export const arrayMock = [
  {
    productDescription: "Sun On Your Back",
    asin: "B094G99RML",
    countReview: 79,
    imgUrl: "https://m.media-amazon.com/images/I/71+WOace3zS._AC_UY218_.jpg",
    price: 0.99,
    retailPrice: 7.99,
    productRating: "4.1 out of 5 stars",
    prime: false,
    dpUrl:
      "/sspa/click?ie=UTF8&spc=MTo3NzM1MTU4MzA0MjQ2ODM4OjE2Njk1NzM1NjY6c3BfYXRmX25leHQ6MjAwNzYxMjU5MDk1MDE6OjA6Og&url=%2FSun-Your-Back-Naira-Khan-ebook%2Fdp%2FB094G99RML%2Fref%3Dsr_1_17_sspa%3Fkeywords%3Dkindle%2Bbook%2Bdeals%26qid%3D1669573566%26s%3Ddigital-text%26sr%3D1-17-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGZfbmV4dA%26psc%3D1",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "Angel Maker: An Unputdownable Scandinavian Crime Thriller With A Chilling Twist (DI Jamie Johansson Book 1)",
    asin: "B08M5SK27G",
    countReview: 7594,
    imgUrl: "https://m.media-amazon.com/images/I/81GPv1R7qeL._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.4 out of 5 stars",
    prime: false,
    dpUrl: "/gp/bestsellers/digital-text/4542588031/ref=sr_bs_1_4542588031_1",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "Those Who Lie: The gripping new thriller you won’t be able to stop talking about",
    asin: "B01MRGTRIF",
    countReview: 815,
    imgUrl: "https://m.media-amazon.com/images/I/81lmZ6k5cfL._AC_UY218_.jpg",
    price: 1.99,
    retailPrice: 8.99,
    productRating: "4.2 out of 5 stars",
    prime: false,
    dpUrl:
      "/Those-Who-Lie-gripping-thriller-ebook/dp/B01MRGTRIF/ref=sr_1_19?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-19",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "Wedding Bells for the Victory Girls: The new uplifting historical fiction saga in the WW2 Shop Girls series (The Shop Girls, Book 6)",
    asin: "B09C7NYHKT",
    countReview: 361,
    imgUrl: "https://m.media-amazon.com/images/I/81uZyCWVW2L._AC_UY218_.jpg",
    price: 2.99,
    retailPrice: 7.99,
    productRating: "4.6 out of 5 stars",
    prime: false,
    dpUrl:
      "/Wedding-Bells-Victory-Girls-historical-ebook/dp/B09C7NYHKT/ref=sr_1_20?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-20",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "The Grave Tattoo: The riveting psychological thriller from the author of Sunday Times crime fiction bestsellers",
    asin: "B002RI9P9K",
    countReview: 6597,
    imgUrl: "https://m.media-amazon.com/images/I/81vLjnkjogL._AC_UY218_.jpg",
    price: 3.99,
    retailPrice: 10.99,
    productRating: "4.2 out of 5 stars",
    prime: false,
    dpUrl:
      "/Grave-Tattoo-Val-McDermid-ebook/dp/B002RI9P9K/ref=sr_1_21?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-21",
    series: null,
    deliveryMessage: null,
    variations: [
      {
        value: "Kindle Edition",
        dpUrl:
          "/Grave-Tattoo-Val-McDermid-ebook/dp/B002RI9P9K/ref=sr_1_19?keywords=kindle+book+deals&qid=1669569201&s=digital-text&sr=1-19",
        price: 3.99,
        prime: false,
        kindleUnlimited: false,
      },
    ],
  },
  {
    productDescription: "The Last Kids on Earth (The Last Kids on Earth)",
    asin: "B07VQS9Q1C",
    countReview: 5042,
    imgUrl: "https://m.media-amazon.com/images/I/91NkR7np2EL._AC_UY218_.jpg",
    price: 3.49,
    retailPrice: 6.99,
    productRating: "4.8 out of 5 stars",
    prime: false,
    dpUrl:
      "/Last-Kids-Earth-Max-Brallier-ebook/dp/B07VQS9Q1C/ref=sr_1_22?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-22",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "Pelican Cove Cozy Mystery Series Box Set 1: Books 1-4 in Pelican Cove Cozy Mysteries",
    asin: "B07Q475TKD",
    countReview: 1410,
    imgUrl: "https://m.media-amazon.com/images/I/61DSmfPUQ4L._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.4 out of 5 stars",
    prime: false,
    dpUrl:
      "/sspa/click?ie=UTF8&spc=MTo3NzM1MTU4MzA0MjQ2ODM4OjE2Njk1NzM1NjY6c3BfbXRmOjIwMDc4NjUwODU2MjA0OjowOjo&url=%2FPelican-Cove-Cozy-Mystery-Box-ebook%2Fdp%2FB07Q475TKD%2Fref%3Dsr_1_23_sspa%3Fkeywords%3Dkindle%2Bbook%2Bdeals%26qid%3D1669573566%26s%3Ddigital-text%26sr%3D1-23-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "Hit and Run (The DI Stella Cole Thrillers Book 1)",
    asin: "B06XY5SQ2L",
    countReview: 4632,
    imgUrl: "https://m.media-amazon.com/images/I/81GiZxFSi4L._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.2 out of 5 stars",
    prime: false,
    dpUrl:
      "/sspa/click?ie=UTF8&spc=MTo3NzM1MTU4MzA0MjQ2ODM4OjE2Njk1NzM1NjY6c3BfbXRmOjIwMDUxNjE2OTkyNjA4OjowOjo&url=%2FHit-Stella-Cole-Thrillers-Book-ebook%2Fdp%2FB06XY5SQ2L%2Fref%3Dsr_1_24_sspa%3Fkeywords%3Dkindle%2Bbook%2Bdeals%26qid%3D1669573566%26s%3Ddigital-text%26sr%3D1-24-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "Where We Belong: The heart-breaking new novel from the bestselling Richard and Judy Book Club author",
    asin: "B07WSGB4JH",
    countReview: 2002,
    imgUrl: "https://m.media-amazon.com/images/I/81n14GnHrDL._AC_UY218_.jpg",
    price: 4.99,
    retailPrice: 8.99,
    productRating: "4.2 out of 5 stars",
    prime: false,
    dpUrl:
      "/Where-We-Belong-Anstey-Harris-ebook/dp/B07WSGB4JH/ref=sr_1_25?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-25",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "London, SE15: A DC Ruth Hunter Murder Case",
    asin: "B09B7Q4CWS",
    countReview: 3873,
    imgUrl: "https://m.media-amazon.com/images/I/81Ko+qrRvAL._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.4 out of 5 stars",
    prime: false,
    dpUrl:
      "/London-SE15-Ruth-Hunter-Murder-ebook/dp/B09B7Q4CWS/ref=sr_1_26?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-26",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "The Traitor: She fell for the enemy. Now she must pay the price. . . (The Mitchells and O’Haras Trilogy, Book 2)",
    asin: "B01MQQLOG7",
    countReview: 1743,
    imgUrl: "https://m.media-amazon.com/images/I/81YQfBgrSLL._AC_UY218_.jpg",
    price: 3.49,
    retailPrice: 7.99,
    productRating: "4.7 out of 5 stars",
    prime: false,
    dpUrl:
      "/Traitor-Mitchells-OHaras-Trilogy-Book-ebook/dp/B01MQQLOG7/ref=sr_1_27?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-27",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "The Butterfly Cove Collection (Butterfly Cove)",
    asin: "B077V1WDKY",
    countReview: 326,
    imgUrl: "https://m.media-amazon.com/images/I/91lF44x8fUL._AC_UY218_.jpg",
    price: 4.99,
    retailPrice: 0,
    productRating: "4.7 out of 5 stars",
    prime: false,
    dpUrl:
      "/Butterfly-Cove-Collection-Sarah-Bennett-ebook/dp/B077V1WDKY/ref=sr_1_28?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-28",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "Temptation (The Hunted Series Book 1)",
    asin: "B00VVG6LMI",
    countReview: 13263,
    imgUrl: "https://m.media-amazon.com/images/I/911JMXrcfiL._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.1 out of 5 stars",
    prime: false,
    dpUrl:
      "/sspa/click?ie=UTF8&spc=MTo3NzM1MTU4MzA0MjQ2ODM4OjE2Njk1NzM1NjY6c3BfbXRmOjIwMDQ5Mjg4MzM5Mzk4OjowOjo&url=%2FTemptation-Hunted-Book-Ivy-Smoak-ebook%2Fdp%2FB00VVG6LMI%2Fref%3Dsr_1_29_sspa%3Fkeywords%3Dkindle%2Bbook%2Bdeals%26qid%3D1669573566%26s%3Ddigital-text%26sr%3D1-29-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "Animal Farm",
    asin: "B07DBS8DL5",
    countReview: 47467,
    imgUrl: "https://m.media-amazon.com/images/I/91S14kngJFL._AC_UY218_.jpg",
    price: 0.99,
    retailPrice: 2.99,
    productRating: "4.6 out of 5 stars",
    prime: false,
    dpUrl:
      "/Animal-Farm-George-Orwell-ebook/dp/B07DBS8DL5/ref=sr_1_30?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-30",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "The Hunting Party: The Sunday Times and New York Times global best seller, a gripping Christmas mystery from the No 1 bestselling author of The Guest List",
    asin: "B07FK6L3T1",
    countReview: 19777,
    imgUrl: "https://m.media-amazon.com/images/I/71AXIhKJvGL._AC_UY218_.jpg",
    price: 3.99,
    retailPrice: 8.99,
    productRating: "4.1 out of 5 stars",
    prime: false,
    dpUrl:
      "/Hunting-Party-gripping-hotly-anticipated-thriller-ebook/dp/B07FK6L3T1/ref=sr_1_31?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-31",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "Her Sister's Child: A heart-stopping psychological thriller with an incredible twist",
    asin: "B08GP5YM7D",
    countReview: 3162,
    imgUrl: "https://m.media-amazon.com/images/I/81r4+HWYfiL._AC_UY218_.jpg",
    price: 1.99,
    retailPrice: 8.99,
    productRating: "4.3 out of 5 stars",
    prime: false,
    dpUrl:
      "/Her-Sisters-Child-heart-stopping-psychological-ebook/dp/B08GP5YM7D/ref=sr_1_32?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-32",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "Snowflakes in the Wind",
    asin: "B01BYBZLYS",
    countReview: 733,
    imgUrl: "https://m.media-amazon.com/images/I/91p5OGMU7lL._AC_UY218_.jpg",
    price: 2.99,
    retailPrice: 8.99,
    productRating: "4.6 out of 5 stars",
    prime: false,
    dpUrl:
      "/Snowflakes-Wind-Rita-Bradshaw-ebook/dp/B01BYBZLYS/ref=sr_1_33?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-33",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "The Amsterdam Affair: A feel-good winter romance (A Romantic Escape Book)",
    asin: "B08KY6GTYC",
    countReview: 1740,
    imgUrl: "https://m.media-amazon.com/images/I/915DZuMPk8L._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.5 out of 5 stars",
    prime: false,
    dpUrl:
      "/sspa/click?ie=UTF8&spc=MTo3NzM1MTU4MzA0MjQ2ODM4OjE2Njk1NzM1NjY6c3BfbXRmOjIwMDM4Njg0OTYyNjA4OjowOjo&url=%2FAmsterdam-Affair-feel-good-romance-Romantic-ebook%2Fdp%2FB08KY6GTYC%2Fref%3Dsr_1_34_sspa%3Fkeywords%3Dkindle%2Bbook%2Bdeals%26qid%3D1669573566%26s%3Ddigital-text%26sr%3D1-34-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "When the Evil Waits (DI Ridpath Crime Thriller Book 6)",
    asin: "B08NB74B9R",
    countReview: 2252,
    imgUrl: "https://m.media-amazon.com/images/I/91PHoJUMFIL._AC_UY218_.jpg",
    price: 1.99,
    retailPrice: 8.99,
    productRating: "4.6 out of 5 stars",
    prime: false,
    dpUrl:
      "/When-Waits-Ridpath-Crime-Thriller-ebook/dp/B08NB74B9R/ref=sr_1_35?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-35",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "Open: An Autobiography",
    asin: "B002VYJYR8",
    countReview: 8457,
    imgUrl: "https://m.media-amazon.com/images/I/91udO6OyvNL._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.6 out of 5 stars",
    prime: false,
    dpUrl:
      "/Open-Autobiography-Andre-Agassi-ebook/dp/B002VYJYR8/ref=sr_1_36?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-36",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription: "The Storyteller of Casablanca",
    asin: "B08V5K7W31",
    countReview: 31347,
    imgUrl: "https://m.media-amazon.com/images/I/81-T5lEbJJL._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "4.5 out of 5 stars",
    prime: false,
    dpUrl: "/gp/bestsellers/digital-text/4542738031/ref=sr_bs_20_4542738031_1",
    series: null,
    deliveryMessage: null,
    variations: [[Object]],
  },
  {
    productDescription:
      "Women with Adult ADHD: An Unconventional Guide to Breaking Through Barriers! Learn Essential Life Skills from Theory to Practice to Deal with ADHD and Stop Feeling Like a Failure",
    asin: "B0BMLMJM97",
    countReview: 266,
    imgUrl: "https://m.media-amazon.com/images/I/71RJTdgQALL._AC_UY218_.jpg",
    price: 0,
    retailPrice: 0,
    productRating: "5.0 out of 5 stars",
    prime: false,
    dpUrl:
      "/Women-Adult-ADHD-Unconventional-Essential-ebook/dp/B0BMLMJM97/ref=sr_1_38?keywords=kindle+book+deals&qid=1669573566&s=digital-text&sr=1-38",
    series: null,
    deliveryMessage: null,
    variations: [
      {
        value: "Kindle Edition",
        dpUrl:
          "/Women-Adult-ADHD-Unconventional-Essential-ebook/dp/B0BMLMJM97/ref=sr_1_32?keywords=kindle+book+deals&qid=1669569201&s=digital-text&sr=1-32",
        price: 0.0,
        prime: false,
        kindleUnlimited: true,
      },
    ],
  },
];
